services:
  # Backend API Service
  - type: web
    name: socialbot-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npx prisma generate && npx prisma db push && npm run db:seed
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: socialbot-database
          property: connectionString

  # Frontend Static Site
  - type: web
    name: socialbot-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: socialbot-backend
          property: host

databases:
  # PostgreSQL Database
  - name: socialbot-database
    plan: free
    databaseName: socialbot
    user: socialbot_user 