services:
  - type: web
    name: socialbot-backend
    runtime: node
    plan: starter
    region: oregon
    buildCommand: |
      nvm use 20
      npm ci
      npx prisma generate
    startCommand: npm start
    preDeployCommand: |
      npm run migrate
      npm run db:seed
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_VERSION
        value: v1
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: BCRYPT_ROUNDS
        value: 12
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: AUTH_RATE_LIMIT_MAX
        value: 10
      - key: LOG_LEVEL
        value: info
      - key: ENABLE_REGISTRATION
        value: true
      - key: ENABLE_VIDEO_UPLOAD
        value: true
      - key: ENABLE_AI_GENERATION
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: socialbot-database
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: socialbot-redis
          property: connectionString

databases:
  - name: socialbot-database
    databaseName: socialbot
    user: socialbot_user
    plan: starter
    region: oregon
    version: "16"

services:
  - type: redis
    name: socialbot-redis
    plan: starter
    region: oregon
    maxmemoryPolicy: allkeys-lru 